name: Submit to Winget Community Repo

on:
  release:
    types: [published]

jobs:
  winget:
    name: Publish winget package
    runs-on: ubuntu-latest
    steps:
      - name: Submit package to Winget Community Repo
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Vencord.Vesktop
          token: ${{ secrets.WINGET_PAT }}
          installers-regex: '\.exe$'
