name: Submit to Winget Community Repo

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: The release tag to submit
        required: true

jobs:
  winget:
    name: Publish winget package
    runs-on: ubuntu-latest
    steps:
      - name: Submit package to Winget Community Repo
        uses: vedantmgoyal2009/winget-releaser@52ef3f3028ed79a9606d7678d0a88d295bc0c690 # v2
        with:
          identifier: Vencord.Vesktop
          token: ${{ secrets.WINGET_PAT }}
          installers-regex: '\.exe$'
          release-tag: ${{ inputs.tag || github.event.release.tag_name }}
